# .github/workflows/azure-nextjs.yml
name: CI/CD – Next.js → Azure App Service

on:
  push:
    branches: [ main ]          # デプロイ対象ブランチを変更する場合はここを修正

env:
  NODE_VERSION: 20

jobs:
  # ------------------------------------------------------------
  # 1. BUILD
  # ------------------------------------------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build      # `.next` フォルダが生成される

      - name: Copy artifact for deployment job
        run: |
          # deploy フォルダを作成（ネストもまとめて）
          mkdir -p deploy/.next

          # 1) アプリ本体
          if [ -d ".next/standalone" ]; then
            cp -R .next/standalone/* deploy/
          else
            cp -R .next/* deploy/.next/
          fi

          # 2) 静的アセット
          cp -R .next/static deploy/.next/

          # 3) public フォルダ（存在すれば）
          if [ -d public ]; then cp -R public deploy/; fi

          # 4) package.json と lockfile（存在すれば）
          cp package.json deploy/
          if [ -f package-lock.json ]; then cp package-lock.json deploy/; fi

      - name: Archive artifact
        run: |
          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: release.zip

  # ------------------------------------------------------------
  # 2. DEPLOY
  # ------------------------------------------------------------
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: release.zip
